### ISSUE TITLE
Invalid Data

### ISSUE THREAD

**Issue by sahasomnath** [rssiweb/attendance#1]
Please update Wednesday, 28th February 2018 timesheet data of Neetu (BLKO18024), it should have the data we have recorded under Ruchi (BLKO18025). As Ruchi was absent for the day so please delete her record for that day.

**Comment by sahasomnath** [comment]
We need to work on this. Edit mode is not working, specially when I am trying to update punch out, the system is not allowing me to do so.

**Comment by sahasomnath** [comment]
![image](https://user-images.githubusercontent.com/26809222/37030557-5f07a550-2161-11e8-8d1b-c723b3775312.png)

We can't close this. It's still showing wrong data. System is not allowing me to delete Ruchi's record.

**Comment by zkhan93** [comment]
this is publicly visible please be aware and try to scratch any personal identifiable information from attachments/photos
coming back to issue which date and is there some error please be a little descriptive..

**Comment by zkhan93** [comment]
I just tried deleting the same record I believe it was on 28th Feb it got deleted. try ctrl+shift+R to clear the browser cache for that page and then try.

**Comment by zkhan93** [comment]
same issue being discussed on #5 please lock this conversation so that all points related to a feature are in one thread.

**Comment by sahasomnath** [comment]
Approved and Closed.
