### ISSUE TITLE
Please see the feedback below on Second draft

### ISSUE THREAD

**Issue by sahasomnath** [rssiweb/attendance#14]
1) Data and format wise (structure) it's approved.
2) Please change the report format pdf.
3) Please change the landing page title to Phoenix.
![image](https://user-images.githubusercontent.com/26809222/38360265-55d0156a-38e7-11e8-9a70-e5e016664899.png)
4) Please change the sequence - ID, Name, Gender, Contact, Email, Password, Confirm Password
![image](https://user-images.githubusercontent.com/26809222/38360373-952bf062-38e7-11e8-84d8-e92e5604bc56.png)
![image](https://user-images.githubusercontent.com/26809222/38360422-bf83879e-38e7-11e8-81e5-a9a929ebfc00.png)
5) Update Password policy. All good except the below highlighted points.
![image](https://user-images.githubusercontent.com/26809222/38360474-e8afb64c-38e7-11e8-868a-a866f55c10ac.png)

6) My Profile page should have Profile picture option.
7) After login right corner of the page should show Welcome, Vivek Kumar with their profile picture in circle or square mode. Also after logic a member should see a home page fist, here it could be their profile page.

8) In Place of lets grow together, please display, Phoenix - A Digital India Initiative
![image](https://user-images.githubusercontent.com/26809222/38360907-4164ad6e-38e9-11e8-878e-ad28f25c0244.png)

**Comment by sahasomnath** [comment]
Any update here. Please treat is urgent.

**Comment by zkhan93** [comment]
except point 2, 5, 6, 7 others are completed
