### ISSUE TITLE
Issue - Second Slot

### ISSUE THREAD

**Issue by sahasomnath** [rssiweb/attendance#16]
1) Need a loading icon while report is running in background, just like we had earlier.
2) Updating student section, after updating student the popup should be auto closed instead of displaying add student popup.
3) We need a screen or any option through which we can edit, update and delete category list.
4) Please share the logic how report is listing the student. We need the report sorted by Category.
5) Place holder of detailed report pop up definitely misguiding user, user has to select here a date which format should be dd/mm/yyyy.

**Comment by zkhan93** [comment]
4. its already sorted by category name - please let me know if you saw some other sorting order
5 - will be a separate issue
