### ISSUE TITLE
Need to display notification that information has been auto saved. Also what happen just in case information dose not get auto saved. So we need a confirmation message.

### ISSUE THREAD

**Issue by sahasomnath** [rssiweb/attendance#19]
![image](https://user-images.githubusercontent.com/26809222/40899118-e2c3e2ce-67e2-11e8-8fc9-39fcc3252147.png)

**Comment by zkhan93** [comment]
as commented in #20 if the information is not saved the error notification will be shown.

**Comment by sahasomnath** [comment]
I agree. But how user will know the information has been auto saved as nothing could be just an assumption. If you are mentioning it anywhere I am good with it.

**Comment by zkhan93** [comment]
This behaviour is adapted from the attendance page. When you put some value on marks there is a loading spinner that will indicate that the data is being saved.

**Comment by sahasomnath** [comment]
Attandance sheet is good. There being disable of a button indicate that information has been saved. Here we don't have anything like that. Please don't mix both.

**Comment by zkhan93** [comment]
so here is what I have done to show that the data being entered is saved.
when someone enterers the marks the processing icon is shown right next to the marks input field (you might not see this if you are on a fast internet connection), one the data is saved on the server the current row will be GREEN for 1 second then turn back to normal color, similarly if the data is not saved the row will turn RED for 1 second and turn back to normal (the data will also be reset)

**Comment by sahasomnath** [comment]
I think we need a discussion here. I agree its working but the way you are confirming no one would be able to understand.

**Comment by sahasomnath** [comment]
![image](https://user-images.githubusercontent.com/26809222/41077695-ce16d552-6a35-11e8-83aa-1aa27a2573a2.png)

The red and green concept is very fine and unnoticeable. please replace it with - can we display a green tick if the information get auto saved. You can use the below image as tick.

![if_tick_mark_dark_1398912 1](https://user-images.githubusercontent.com/26809222/41077761-30523702-6a36-11e8-9f76-451ec537d6bd.png)

**Comment by zkhan93** [comment]
Okay, if you have the idea you should tell it while filing the bug, so that the time is saved for both of us, don't wait for my solution and then come up with yours.

**Comment by zkhan93** [comment]
as discussed, highlighting row with a color is the final solution, but it seems that the colors are not properly visible on some screens, will make them more vibrant.
