### ISSUE TITLE
Add button to delete marks entered for a test

### ISSUE THREAD

**Issue by sahasomnath** [rssiweb/attendance#20]

**Comment by zkhan93** [comment]
there is a loading, icon visible as soon as marks are entered, in case of failure it will show a notification, with error, showing notification on every action will create a lot of notifications.

strongly related to #19 close this and dicuss on #19 to have discussion on same page

**Comment by sahasomnath** [comment]
Hey, this issue is related to reset button. it has nothing to do with auto save.

**Comment by zkhan93** [comment]
As soon as user input some marks, it is getting save in backend, if you want a reset button to clear records on a page it will be deleting all the marks recorded for that test. Do you really want that ?

**Comment by sahasomnath** [comment]
Yes please. Delete all is the correct term. Thanks. Please don't forget to add notification pop-up on that particular button.

**Comment by sahasomnath** [comment]
![image](https://user-images.githubusercontent.com/26809222/41077251-2e932956-6a33-11e8-9979-625a8bffae87.png)

Please make it Y instead of y. Rest Functionality is working. I'll close it after you fix the text.

**Comment by sahasomnath** [comment]
Also please remove "" from test name. Test name is already in CAPS so user will be bale able to understand it easily.
