### ISSUE TITLE
Please ensure you are displaying institute's name as RSSI not BRSSI.

### ISSUE THREAD

**Issue by sahasomnath** [rssiweb/attendance#22]
![image](https://user-images.githubusercontent.com/26809222/40969538-c5e32478-68d5-11e8-897f-d6b6d53e3adc.png)

**Comment by zkhan93** [comment]
that is hardcoded and will go away with the redesigning of the profile page.

**Comment by zkhan93** [comment]
fixed in 4d2b0deba681638c5391422594e846fc8453fce1

**Comment by sahasomnath** [comment]
Approved and Closed.
