### ISSUE TITLE
Why editing number is not getting reflected after refreshing the page.

### ISSUE THREAD

**Issue by sahasomnath** [rssiweb/attendance#23]
![image](https://user-images.githubusercontent.com/26809222/40969768-65fc8346-68d6-11e8-967a-1f3011ce43f4.png)

I have updated few numbers and when I am re-logging again logically it should show new updated values but its not doing the same. Please look into it.

**Comment by zkhan93** [comment]
well, I need more details on this one, are you entering a number greater than max marks? 

when you enter marks greater than max marks, its simply says on the UI and does not get saved in the backend. I will raise notification in this case.

**Comment by sahasomnath** [comment]
No I have entered valid marks.

**Comment by zkhan93** [comment]
I am not able to see when this occurs exactly, please set up a meeting to show me when you are encountering this behaviour.

**Comment by sahasomnath** [comment]
It's working. thank you. Approved and Closed.
