### ISSUE TITLE
Why Student list is not showing Inactive Students. It should show everyone. Is not it?

### ISSUE THREAD

**Issue by sahasomnath** [rssiweb/attendance#25]
![image](https://user-images.githubusercontent.com/26809222/40975175-b398982c-68e7-11e8-9a36-84766bc83887.png)

**Comment by zkhan93** [comment]
currently, only active students are listed.
how do you want to see inactive ones? via some switch or you want to see them all at once.

**Comment by sahasomnath** [comment]
![image](https://user-images.githubusercontent.com/26809222/41078003-be265bca-6a37-11e8-83ca-ed9db5db1f71.png)

Still its not sorted correctly. First sorting by Student Status and then Student ID (Serial number should be proper 1,2,3,4....)

**Comment by zkhan93** [comment]
The client side sorting is on user the serial number is according to the first order in which the list is rendered, after you manually sort it by clicking on a column, I cannot fix the serial number.

**Comment by zkhan93** [comment]
sorting order is state, cat, name and I belive its enough.
