### ISSUE TITLE
change website logo

### ISSUE THREAD

**Issue by sahasomnath** [rssiweb/attendance#3]
Please update the logo. I have removed its background and size is 50*50. Ensure you are using the same. Please download it from [here](https://drive.google.com/file/d/1yd8wmjT7XmMEH9sqzKhL_2eJI9qTAFpo/view).

**Comment by zkhan93** [comment]
can you provide a icon with better resolution..50*50 i think is very low if you want clear view of the logo 100*100 should be fine.

**Comment by sahasomnath** [comment]
I agree with you Zee. So, what you need? Cant you change it to 50*50 instead of 100*100. Please let me know.

**Comment by sahasomnath** [comment]
Approved and Closed.
