### ISSUE TITLE
System is not allowing me to enter 0 as marks. Its treating 0 as invalid.

### ISSUE THREAD

**Issue by sahasomnath** [rssiweb/attendance#33]
![image](https://user-images.githubusercontent.com/26809222/42300744-931810d2-802f-11e8-8cc7-09845febdbe2.png)

![image](https://user-images.githubusercontent.com/26809222/42300739-8abc4552-802f-11e8-8d55-264afcbe3c40.png)

**Comment by zkhan93** [comment]
this is fixed and released with 9d370f6e30c483e1a42acdab332fb8b8e928e31f

**Comment by sahasomnath** [comment]
Approved.
