### ISSUE TITLE
change in import students include new field 

### ISSUE THREAD

**Issue by sahasomnath** [rssiweb/attendance#6]
Need to update student section (Import Students logic), Import file should not include the students marked as R. Also need to change the logic behind date of birth as currently it’s considering the change in Age which we are calculating based on DOB and System date.

**Comment by sahasomnath** [comment]
Any update here? Please note as per the student data base we may have multiple status (Currently we have R, W etc) so you have to ensure that we are not including any students having R their status.

**Comment by zkhan93** [comment]
Add a button for students to activate and deactivate a students page,
a deactivated student will not be listed in attendance sheet.

## Report:
Monthly report - no inactive student
Detailed Report - Active/Inactive filter

**Comment by zkhan93** [comment]
We agreed that having a button will cause data sync issue, hence no button for deactivating a student.
so we added effective end date for a student after which he will not be visible in the export export
