### ISSUE TITLE
create faculties page

### ISSUE THREAD

**Issue by sahasomnath** [rssiweb/attendance#7]
Faculties section need to be updated with the shared details (i.e. Email Address and Name of the users).

**Comment by sahasomnath** [comment]
We can't close this one. Please let me know once you have time to discuss.
-- Issue in password reset.
-- Pending item, Faculty data import just like student one.

**Comment by sahasomnath** [comment]
Password reset is not working Zee. Same with Faculty information update. Please let me know if we have any progress here.

**Comment by zkhan93** [comment]
one time faculty loaded, with a default password and add faculty feature was already working, please close this issue.
